# Generated by Django 4.2.1 on 2023-05-25 23:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='joblisting',
            new_name='job_listing',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicationdate',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicationfeedback',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicationstatus',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='jobseeker',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.jobseeker'),
        ),
    ]
