# Generated by Django 4.2.1 on 2023-05-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.user'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.user'),
        ),
    ]
