# Generated by Django 4.2.1 on 2023-05-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_joblisting_jobapplication_job_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='jobseeker',
        ),
    ]
