# Generated by Django 4.2.1 on 2023-05-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_userjob_employer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userjob_type',
        ),
    ]
