# Generated by Django 4.2.1 on 2023-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='name',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.CharField(default='bio', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(default='location', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(default='0000000000', max_length=50),
        ),
    ]
