# Generated by Django 4.2.1 on 2023-05-26 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='save_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
