# Generated by Django 4.2.1 on 2023-05-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_jobseeker_email_remove_jobseeker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='jobrequirements',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(max_length=250),
        ),
    ]
