# Generated by Django 4.2.1 on 2023-06-03 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_resume_certifications_alter_resume_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_date', models.DateField(default=datetime.date.today)),
                ('employer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.employer')),
                ('job_seeker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.jobseeker')),
            ],
        ),
    ]
